/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ConsultasRouteImport } from './routes/consultas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as MedicosIndexRouteImport } from './routes/medicos.index'
import { Route as PacientesNovoRouteImport } from './routes/pacientes.novo'
import { Route as MedicosNovoRouteImport } from './routes/medicos.novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRoute = ConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosIndexRoute = MedicosIndexRouteImport.update({
  id: '/medicos/',
  path: '/medicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesNovoRoute = PacientesNovoRouteImport.update({
  id: '/pacientes/novo',
  path: '/pacientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosNovoRoute = MedicosNovoRouteImport.update({
  id: '/medicos/novo',
  path: '/medicos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/especialidades': typeof EspecialidadesRoute
  '/login': typeof LoginRoute
  '/medicos/novo': typeof MedicosNovoRoute
  '/pacientes/novo': typeof PacientesNovoRoute
  '/medicos/': typeof MedicosIndexRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/especialidades': typeof EspecialidadesRoute
  '/login': typeof LoginRoute
  '/medicos/novo': typeof MedicosNovoRoute
  '/pacientes/novo': typeof PacientesNovoRoute
  '/medicos': typeof MedicosIndexRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultas': typeof ConsultasRoute
  '/especialidades': typeof EspecialidadesRoute
  '/login': typeof LoginRoute
  '/medicos/novo': typeof MedicosNovoRoute
  '/pacientes/novo': typeof PacientesNovoRoute
  '/medicos/': typeof MedicosIndexRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultas'
    | '/especialidades'
    | '/login'
    | '/medicos/novo'
    | '/pacientes/novo'
    | '/medicos/'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultas'
    | '/especialidades'
    | '/login'
    | '/medicos/novo'
    | '/pacientes/novo'
    | '/medicos'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/consultas'
    | '/especialidades'
    | '/login'
    | '/medicos/novo'
    | '/pacientes/novo'
    | '/medicos/'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultasRoute: typeof ConsultasRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  LoginRoute: typeof LoginRoute
  MedicosNovoRoute: typeof MedicosNovoRoute
  PacientesNovoRoute: typeof PacientesNovoRoute
  MedicosIndexRoute: typeof MedicosIndexRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/': {
      id: '/medicos/'
      path: '/medicos'
      fullPath: '/medicos/'
      preLoaderRoute: typeof MedicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/novo': {
      id: '/pacientes/novo'
      path: '/pacientes/novo'
      fullPath: '/pacientes/novo'
      preLoaderRoute: typeof PacientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos/novo': {
      id: '/medicos/novo'
      path: '/medicos/novo'
      fullPath: '/medicos/novo'
      preLoaderRoute: typeof MedicosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultasRoute: ConsultasRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  LoginRoute: LoginRoute,
  MedicosNovoRoute: MedicosNovoRoute,
  PacientesNovoRoute: PacientesNovoRoute,
  MedicosIndexRoute: MedicosIndexRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
